### ISSUE TITLE
Add feautures for load new style string

### ISSUE THREAD

**Issue by Jomart02** [Jomart02/QssStyleManager#1]
# Need to add support for adding style lines to the end of the installed one

## Example

```json
   "stringStyle": " QWidget {backgroung-color : red;} QLabel {color: {colorText}; }

```
### First style
```css
QDoubleSpinBox {color: {colorText}};
```

### Result style
```css
QDoubleSpinBox {color: {colorText}};
QWidget {backgroung-color : red;} QLabel {color: {colorText};
```
After that swap all keys style

This key is checked at the very beginning of reading and is written to the end of the installed style file
This key must be unique and not replaceable
